### ISSUE TITLE
Follow what is possible in Front-End Checklist

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/shgysk8zer0.github.io#94]
See [Front-End Checklist](https://github.com/thedaviddias/Front-End-Checklist)

Most prominently:
- [x] Set `<meta http-equiv="x-ua-compatible" content="ie=edge">`
- [x] Add Apple touch icon
- [x] Add Windows tile
- [x] Add [Social media `<meta>`s](https://github.com/thedaviddias/Front-End-Checklist#social-meta)

There will be a separate issue for image optimization
